#!/bin/bash
set -x

SCRIPT_DIR=`dirname "$0"`"/scripts"
SCRIPT_DIR=`readlink -f $SCRIPT_DIR`
ZSH_SETUP_DIR=`dirname "$0"`"/zsh_setup"
ZSHRC="$HOME/.zshrc"

function get_package_manager {
    if `which apt-get > /dev/null`; then
        echo "apt-get"
    elif `which dnf > /dev/null`; then
        echo "dnf"
    fi
}

setup_order=(
    "$SCRIPT_DIR" 
    "$ZSH_SETUP_DIR"
)

function yes_or_no {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0 ;;  
            [Nn]*) echo "Aborted"; return 1 ;;
        esac
    done
}

function setup {
    export TUXINIT_PACKAGE_MANAGER=`get_package_manager`
    echo using $TUXINIT_PACKAGE_MANAGER package manager
    if [ ! -e "$ZSHRC" ] ; then
        echo "# generated by tuxit.sh" > "$ZSHRC"
    fi
    echo "script directory: $SCRIPT_DIR"
    for script_dir in "${setup_order[@]}"; do
        for script in `ls -d -1 "$script_dir/"*.sh`; do
            header="# =====`basename $script`====="
            echo "CHECK: $header"
            if [[ `grep -oxF "$header" "$ZSHRC"` != "$header" ]]; then
                echo "$header" >> "$ZSHRC"
                $script "$ZSHRC"
                
            fi
        done
    done
    unset TUXINIT_PACKAGE_MANAGER
    source "$ZSHRC"
}

if [[ "$EUID" = 0 ]]; then
    echo "(1) already root"
    yes_or_no "Are you sure you want to setup up the root user?" && setup
else
    sudo -k # make sure to ask for password on next sudo
    if sudo true; then
        echo "(2) correct password"
        setup
    else
        echo "(3) wrong password"
        exit 1
    fi
fi

echo "finished"
